### PR TITLE
Fixed issues with Huawei FS create form. Fixes #453 and #454

### LINKED ISSUE #453: [Multi-Cloud FileShare] Need to support for protocol drop-down for multiple protocol selections
**Issue/Feature Description:** Need to enhance the Fileshare Creation form to have drop-down box for protocols selection for the respective cloud backends

**Why this issue to fixed / feature is needed(give scenarios or use cases):** To enhance Fileshare Creation

**How to reproduce, in case of a bug:**

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

### PR DESCRIPTION
**Pull request by anvithks**
**What type of PR is this?**
/kind bug fix

**What this PR does / why we need it**:
This PR fixes the issues with the Cloud fileshare create form size field when Huawei File Share backend is selected and then changed to GCP or Azure backend.
This PR also allows user to select multiple protocols in Huawei File share backend based on the support. Currently only NFS is added.

**Which issue(s) this PR fixes**:

Fixes #453 #454 

**Test Report Added?**:
/kind TESTED

**Test Report**:
image

**Special notes for your reviewer**:

### CODE REVIEW

File: src/app/business/block/cloud-file-share/create/cloud-file-share-create.component.ts [hunk 1]
```diff
@@ -99,6 +101,13 @@ export class CloudFileShareCreateComponent implements OnInit{
             'description': new FormControl('', {validators:[Validators.maxLength(250),Validators.pattern(this.validRule.description)]}),
             'type' : new FormControl('cloudFS')
         });
+
+        this.protocolTypeOptions = [
```
Comment (himanshuvar) [inline src/app/business/block/cloud-file-share/create/cloud-file-share-create.component.ts:105]: Please add {
                label: 'CIFS',
                value: 'CIFS'
            }

**Review by himanshuvar — CHANGES_REQUESTED** [review]
About MultiSelect Checkbox Size, Text is coming out, Can we fix the size?

**Comment by anvithks** [comment]
> About MultiSelect Checkbox Size, Text is coming out, Can we fix the size?

Will check post release.

File: src/app/business/block/cloud-file-share/create/cloud-file-share-create.component.ts (hunk 1 above)
Comment (anvithks) [reply src/app/business/block/cloud-file-share/create/cloud-file-share-create.component.ts:105]: I have this ready. Since I did not receive any update I just retained NFS.

**Review by himanshuvar — APPROVED** [review]
LGTM

Please open an issue to track Checkbox Text Size

**Review by kumarashit — APPROVED** [review]
LGTM

**Review by skdwriting — APPROVED** [review]
LGTM
