### PR TITLE
Fixed the display issues in profile card. Removed replication label for profiles without replication enabled. Added more display information to Capacity charts

### LINKED ISSUE #579: Profile card capacity usage chart does not have a legend. Replication label is shown for profiles that do not have replication enabled.
**Issue/Feature Description:**
The profile card has the following issues:
- the pool capacity usage chart is not immediately clear as there is no legend or a title.
- replication label is displayed for profiles where replication is not enabled.
- 
**Why this issue to fixed / feature is needed(give scenarios or use cases):**
Improve the user experience and fix display issues.

**How to reproduce, in case of a bug:**
1. Login to SODA dashboard
2. Navigate to Profiles.
3. Create a new profile by clicking on `Create`
4. In the profile list page you will see a profile card with the `Replication` label
5. The Capacity usage chart will be visible without any legend .

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**
profile-card-issues-001

### PR DESCRIPTION
**Pull request by anvithks**
**What type of PR is this?**
 /kind bug fix

**What this PR does / why we need it**:
This PR fixes the following issues of the profile card UI:
- Add legend and title for the capacity chart in profile card.
- Remove the `replication` label from profile cards that do not have replication enabled.
- 
**Which issue(s) this PR fixes**:
Fixes #579 

**Test Report Added?**:
/kind TESTED

**Test Report**:
profile-card-improve-001
profile-card-improve-002

profile-card-improve-003

**UPDATE :**
Added unit to the capacity in the legend
image

image

image

**Special notes for your reviewer**:

### CODE REVIEW

**Review by asifdxtreme — APPROVED** [review]
LGTM

**Comment by kumarashit** [comment]
The Capacity Legend doesn't have Unit?

**Comment by anvithks** [comment]
> The Capacity Legend doesn't have Unit?

@kumarashit Added the unit to the legend.

image

image

image

File: src/app/business/profile/profileCard/profile-card.component.ts [hunk 1]
```diff
@@ -147,7 +151,7 @@ export class ProfileCardComponent implements OnInit {
             this.isAdministrator = false;
         }
         this.chartDatas = {
-            labels: ['Unused Capacity', 'Used Capacity'],
+            labels: ['Unused Capacity (GB)', 'Used Capacity (GB)'],
```
Comment (kumarashit) [inline src/app/business/profile/profileCard/profile-card.component.ts:154]: Is GB the highest unit we convert and display?

Comment (anvithks) [reply src/app/business/profile/profileCard/profile-card.component.ts:154]: This is for profile @kumarashit . It shows the pool capacity that is assigned, which is fixed to 10 GB.

Comment (kumarashit) [reply src/app/business/profile/profileCard/profile-card.component.ts:154]: Is it fixed at 10GB?

Comment (anvithks) [reply src/app/business/profile/profileCard/profile-card.component.ts:154]: Yes.

**Review by skdwriting — APPROVED** [review]
LGTM

File: src/app/business/profile/profileCard/profile-card.component.ts (hunk 1 above)
Comment (anvithks) [reply src/app/business/profile/profileCard/profile-card.component.ts:154]: @kumarashit After checking with @PravinRanjan10 I have concluded that the response is returned in GB for all drivers. 
This will work across the board for all drivers as of now. 
If there is a change we will update accordingly.
Changing the response of the pool capacity API is outside the scope of this PR.
Please review and approve.

**Review by kumarashit — APPROVED** [review]
LGTM
