### PR TITLE
[Hw-SFS FileShare Support] Implement Hw Cloud SFS FileShare Dashboard Support for Multi-Cloud

### LINKED ISSUE #451: [Multicloud UI] Support for Hw Cloud SFS for Multi-Cloud FileShare
**Issue/Feature Description:** Enhance Cloud file share service to provide support for Huawei SFS

**Why this issue to fixed / feature is needed(give scenarios or use cases):** This PR is needed to support Fileshare operations for SFS Huawei Cloud

**How to reproduce, in case of a bug:**

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

### PR DESCRIPTION
**Pull request by himanshuvar**
**What type of PR is this?**
> /kind new feature

**What this PR does / why we need it**:  This PR is for Huawei Cloud SFS FileShare Dashboard Support for multi-cloud. This PR is having the following highlights:

* Added Register backend support for Hw Cloud SFS                                                                                                                            
* Implemented Hw Cloud SFS Creation
* Implemented Hw Cloud SFS Updation
* Added Protocols support field for Fileshare API
* List/Get/Delete FS remains As-Is                                                                                                                                         
* Updated Text/Space formatting

**Which issue(s) this PR fixes**:

Fixes #451 

**Test Report Added?**:
> /kind TESTED

**Test Report**:

FileShare Operations for Huawei SFS done as follows:

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by anvithks** [comment]
@himanshuvar Could you please attach some screenshots for all the changes added. It will help to review.
Thanks.

**Review by anvithks — CHANGES_REQUESTED** [review]
@himanshuvar seems like the cloud-file-share-modify.component.html is not added.

File: src/app/business/block/cloud-file-share/create/cloud-file-share-create.component.ts [hunk 1]
```diff
@@ -195,7 +216,32 @@ export class CloudFileShareCreateComponent implements OnInit{
...
+                    (value:string)=>{
+                        this.sfsType = value
+                    }
+                );
+            }
+
+            this.cloudFileShareCreateForm.addControl('size', this.fb.control('1', [Validators.required]));
+            this.cloudFileShareCreateForm.addControl('availabilityZone', this.fb.control(''));
+            this.cloudFileShareCreateForm.addControl('encrypted', this.fb.control(false, [Validators.required]));
+            this.cloudFileShareCreateForm.addControl('protocols', this.fb.control('NFS'));
```
Comment (anvithks) [inline src/app/business/block/cloud-file-share/create/cloud-file-share-create.component.ts:234]: Is `protocols` always going to be `NFS` ?
Can there be any other type of protocol?

File: src/app/business/block/cloud-file-share/create/cloud-file-share-create.component.ts [hunk 2]
```diff
@@ -318,6 +375,11 @@ export class CloudFileShareCreateComponent implements OnInit{
         if(value['tags']){
             dataArr['tags'] = value['tags'];
         }
+        if(value['protocols']){
+            var protoArr:string[];
+            protoArr = [value['protocols']]
```
Comment (anvithks) [inline src/app/business/block/cloud-file-share/create/cloud-file-share-create.component.ts:380]: what is the value that protocols is expecting in the backend?
is it an array of one element or an array of strings?

File: src/app/business/block/cloud-file-share/create/cloud-file-share-create.component.html [hunk 3]
```diff
@@ -10,21 +10,27 @@ <h1>{{i18n.keyID['sds_creatFileShare']}}</h1>
     <form-item label="{{label.backend}}" [required]="true">
         <p-dropdown [style]="{'min-width':'150px','width':'220px'}" placeholder="Please select" [options]="backendsOption" (onChange)="updateFormAndRegion()" formControlName="backend"></p-dropdown>
     </form-item>
+    <form-item *ngIf="cloudFileShareCreateForm.controls['sfsType']" label="{{label.sfs_type}}" [required]="true">
+        <span *ngIf = "false"><p-radioButton label="Auto" formControlName="sfsType" name="typeRadioGroup" value="Auto"></p-radioButton></span>
```
Comment (anvithks) [inline src/app/business/block/cloud-file-share/create/cloud-file-share-create.component.html:14]: Is this field always hidden?
`*ngIf = "false"` will set it to false always.

**Review by anvithks — CHANGES_REQUESTED** [review]
@himanshuvar I have a few questions which I have added in this review. Overall LGTM but need to see the screenshots of how all the pages look when the changes are incorporated. Please do add screenshots for the changed pages.

**Comment by himanshuvar** [comment]
> 
> 
> @himanshuvar seems like the cloud-file-share-modify.component.html is not added.

No changes in the View for cloud-file-share-modify, So cloud-file-share-modify.component.html is not added

**Comment by himanshuvar** [comment]
> 
> 
> @himanshuvar Could you please attach some screenshots for all the changes added. It will help to review.
> Thanks.

@anvithks Added the screenshots. Thanks

File: src/app/business/block/cloud-file-share/create/cloud-file-share-create.component.ts (hunk 1 above)
Comment (himanshuvar) [reply src/app/business/block/cloud-file-share/create/cloud-file-share-create.component.ts:234]: No Protocol will not be NFS always. NFS is added as a default protocol.
There can be other protocols like NFS, CIFS, SAMBA etc.
You can raise an issue to enhance the protocol field as a Drop Down menu

File: src/app/business/block/cloud-file-share/create/cloud-file-share-create.component.ts (hunk 2 above)
Comment (himanshuvar) [reply src/app/business/block/cloud-file-share/create/cloud-file-share-create.component.ts:380]: Its an Array of string. It can have multiple values also.

File: src/app/business/block/cloud-file-share/create/cloud-file-share-create.component.html (hunk 3 above)
Comment (himanshuvar) [reply src/app/business/block/cloud-file-share/create/cloud-file-share-create.component.html:14]: always hidden means?

File: src/app/business/block/cloud-file-share/create/cloud-file-share-create.component.ts (hunk 1 above)
Comment (anvithks) [reply src/app/business/block/cloud-file-share/create/cloud-file-share-create.component.ts:234]: In that case please let me know the possible values for the protocols that are supported as follows:
```
[
            {
                label: 'NFS',
                value: 'NFS'
            }
        ];
```
Are the values expected in uppercase or lowercase?
I will make the necessary changes and push them to your branch.

File: src/app/business/block/cloud-file-share/create/cloud-file-share-create.component.ts (hunk 2 above)
Comment (anvithks) [reply src/app/business/block/cloud-file-share/create/cloud-file-share-create.component.ts:380]: In this instead of building the array we can just loop through the `value['protocols ']` and the push() method.
The current code will only add the one value always.

File: src/app/business/block/cloud-file-share/create/cloud-file-share-create.component.html (hunk 3 above)
Comment (anvithks) [reply src/app/business/block/cloud-file-share/create/cloud-file-share-create.component.html:14]:
```
<span *ngIf = "false"><p-radioButton label="Auto" formControlName....
```
here ngIf is set to false. There is no check on any variable. So not sure what the check is there for.
Where is the `Auto` value used?
In the screenshot above I see only `SFS` and `SFS_Turbo` as the options.

**Comment by anvithks** [comment]
> > @himanshuvar seems like the cloud-file-share-modify.component.html is not added.
> 
> No changes in the View for cloud-file-share-modify, So cloud-file-share-modify.component.html is not added

If the `protocol` and `SFS type` fields cannot be modified then they need to be displayed to the user as they are fields specific to HW FS. If they can be modified then the user needs to be able to make the changes.
let me know and I will help make these changes.

**Comment by anvithks** [comment]
> > @himanshuvar Could you please attach some screenshots for all the changes added. It will help to review.
> > Thanks.
> 
> @anvithks Added the screenshots. Thanks

Thanks @himanshuvar .
This is great work.

File: src/app/business/block/cloud-file-share/create/cloud-file-share-create.component.ts (hunk 1 above)
Comment (himanshuvar) [reply src/app/business/block/cloud-file-share/create/cloud-file-share-create.component.ts:234]: Issue is opened for the enhancement for protocols selection through drop down menu.
We can enhance and track the FS enhancement support separately. 
https://github.com/sodafoundation/dashboard/issues/453

File: src/app/business/block/cloud-file-share/create/cloud-file-share-create.component.ts (hunk 2 above)
Comment (himanshuvar) [reply src/app/business/block/cloud-file-share/create/cloud-file-share-create.component.ts:380]: Yes, Protocols can be enhanced for drop-down menu.
We can enhance and track the FS enhancement support separately.
#453

File: src/app/business/block/cloud-file-share/create/cloud-file-share-create.component.html (hunk 3 above)
Comment (himanshuvar) [reply src/app/business/block/cloud-file-share/create/cloud-file-share-create.component.html]: Thanks, Done

**Comment by himanshuvar** [comment]
> 
> 
> > > @himanshuvar seems like the cloud-file-share-modify.component.html is not added.
> > 
> > 
> > No changes in the View for cloud-file-share-modify, So cloud-file-share-modify.component.html is not added
> 
> If the `protocol` and `SFS type` fields cannot be modified then they need to be displayed to the user as they are fields specific to HW FS. If they can be modified then the user needs to be able to make the changes.
> let me know and I will help make these changes.

IMHO We should show only the editable fields on the Update Form.

**Comment by anvithks** [comment]
@himanshuvar Are there any conditional changes based on whether the `SFS Type` is `SFS` or `SFS_Turbo` ?
Are the protocols supported same for both the options?

**Review by anvithks — APPROVED** [review]
LGTM
There are a few issues that will be raised and handled subsequently.

**Comment by skdwriting** [comment]
@anvithks @kumarashit please check and approve
@anvithks default size issue - please raise the issue and PR.
Then we can merge this PR

**Review by kumarashit — APPROVED** [review]
LGTM
